Fix sycl_header alias for backward compatibility  (#254)
This PR resolves the following failure encountered while running bazel
query "deps(//xla/...)":

ERROR: Evaluation of query "deps(//xla/...)" failed: preloading
transitive closure failed: no such target
'@@local_config_sycl//sycl:sycl_headers': target 'sycl_headers' not
declared in package 'sycl' defined by
/home/mraunak/.cache/bazel/_bazel_mraunak/.../external/local_config_sycl/sycl/BUILD

The issue was caused by the missing sycl_headers target in the
@local_config_sycl repository, which this PR addresses.