[oneAPI]Fix icpx wrapper to resolving linking error (#221)
This change fixes a build issue where importing jax failed with the
error:

ImportError: jaxlib/_jax.so: undefined symbol: Wrapped_PyInit__jax

The root cause was incorrect handling of linker flags in icpx_wrapper
during the link stage. The wrapper was rewriting and deduplicating
linker arguments, which unintentionally broke the original
--whole-archive / --no-whole-archive grouping emitted by Bazel. As a
result, the archive:
bazel-out/k8-opt/bin/jaxlib/lib_jax_pywrap_library.pic.a
was no longer inside the --whole-archive region, preventing the linker
from pulling in the object that defines Wrapped_PyInit__jax.
Consequently, the symbol was not included in libjax_common.so, leading
to the runtime failure