Upgrade oneAPI toolchain to 2025.3 (#212)
This PR upgrades the oneAPI toolchain from 2025.1 to 2025.3.

1. The flag "-Wno-implicit-float-size-conversion" was removed as it gave
the error below when compiled with the new version of Clang 21.
error: unknown warning option '-Wno-implicit-float-size-conversion'
[-Werror,-Wunknown-warning-option]

2.
"compiler/{oneapi_version}/lib/libur_loader.so.0".format(oneapi_version
= ONEAPI_VERSION), was redundant, hence removed

3. tbb/mkl/dnnl files were removed, as we are currently proceeding with
the minimal set of libraries needed to run XLA. If needed in the future,
we will add those back.