Add missing defines capture for cuda_library (#233)
We (zml/zml) depend on openxla/xla heavily and reuse some parts of
`rules_ml_toolchain`.

---

In `cuda_library` `defines` is added unconditionally, but is not
captured, causing:

```
ERROR: Traceback (most recent call last):
        File "/home/corentin/xla/xla/stream_executor/cuda/BUILD", line 405, column 13, in <toplevel>
                cuda_library(
        File "/home/corentin/xla/cuda.bzl", line 14, column 18, in cuda_library
                _cuda_library(
        File "/home/corentin/.cache/bazel/_bazel_corentin/a36dc9fa8ce05c0b963c2b64a7d99644/external/rules_ml_toolchain++cuda_configure_ext+local_config_cuda/cuda/build_defs.bzl", line 183, column 22, in cuda_library
                native.cc_library(
Error in cc_library: rule(...) got multiple values for parameter 'defines'
```

if `defines` is also passed as `cuda_library` call site.